routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('dashboard.index');

    // profile
    Route::get('/profile', 'HomeController@profile')->name('user.profile');
    Route::post('/profile', 'HomeController@editProfile')->name('user.editProfile');

    // end profile

    // sliders routes
    Route::get('sliders-data', 'SliderController@data')->name('sliders.data');
    Route::post('sliders-bulkDelete', 'SliderController@bulkDelete')->name('sliders.bulkDelete');
    Route::resource('sliders', 'SliderController')->except('show');
    //end sliders routes

    // about routes
    Route::get('about-data', 'AboutController@data')->name('about.data');
    Route::post('about-bulkDelete', 'AboutController@bulkDelete')->name('about.bulkDelete');
    Route::resource('about', 'AboutController')->except('show');
    //end about routes

    // customers routes
    Route::get('customers-data', 'CustomerController@data')->name('customers.data');
    Route::post('customers-bulkDelete', 'CustomerController@bulkDelete')->name('customers.bulkDelete');
    Route::resource('customers', 'CustomerController')->except('show');
    //end customers routes

    // blogs routes
    Route::get('blogs-data', 'BlogController@data')->name('blogs.data');
    Route::post('blogs-bulkDelete', 'BlogController@bulkDelete')->name('blogs.bulkDelete');
    Route::resource('blogs', 'BlogController')->except('show');
    //end customers routes

    // categories routes
    Route::get('categories-data', 'CategoryController@data')->name('categories.data');
    Route::post('categories-bulkDelete', 'CategoryController@bulkDelete')->name('categories.bulkDelete');
    Route::resource('categories', 'CategoryController')->except('show');
    //end categories routes

    // services routes
    Route::get('services-data', 'ServiceController@data')->name('services.data');
    Route::post('services-bulkDelete', 'ServiceController@bulkDelete')->name('services.bulkDelete');
    Route::resource('services', 'ServiceController')->except('show');
    //end services routes

    // Health Care Section routes
    Route::get('health-care-data', 'HealthCareSectionController@data')->name('health-care.data');
    Route::post('health-care-bulkDelete', 'HealthCareSectionController@bulkDelete')->name('health-care.bulkDelete');
    Route::resource('health-care', 'HealthCareSectionController')->except('show');
    //end  Health Care Section routes

    //pages
    Route::get('pages-data', 'PageController@data')->name('pages.data');
    Route::resource('pages', 'PageController')->except('show');
    //end pages

    // projects routes
    Route::get('contact-us-data', 'ContactUsController@data')->name('contact-us.data');
    Route::post('contact-us-bulkDelete', 'ContactUsController@bulkDelete')->name('contact-us.bulkDelete');
    Route::resource('contact-us', 'ContactUsController')->except('show');
    //end customers routes

    // settings
    Route::get('settings', 'SettingController@index')->name('settings.index');
    Route::post('settings', 'SettingController@store')->name('settings.store');
    // end settings


});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::namespace('Website')->group(function () {

    // home
    Route::get('/', 'FrontController@index')->name('home');
    // end home

    // about
    Route::get('about', 'AboutController@index');
    // end about

    // categories
    Route::get('categories', 'CategoryController@index');
    Route::get('categories/{id}', 'CategoryController@show');
    // end categories


    // blogs
    Route::get('blogs', 'BlogController@index');
    Route::get('blogs/{id}', 'BlogController@show');
    // end blogs

    //contact us
    Route::get('contact-us', 'ContactUsController@index');
    Route::post('contact-us', 'ContactUsController@post')->name('website.contactUs');
    // end contact us
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{

    protected $table = 'categories';
    protected $guarded = [];
    protected $appends = ['image'];

    protected $with = 'photo';

    public function photo()
    {

        return $this->morphOne(Photo::class, 'photoable');

    }//end of photo function

    public function getImageAttribute()
    {

        if ($this->photo == '') {
            return asset('default.svg');
        }

        return asset('images/categories/' . $this->photo->src);


    }//end of getImageAttribute function
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Helper\UploadTrait;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class CategoryController extends Controller
{
    use UploadTrait;

    public function index()
    {

        return view('dashboard.categories.index');
    }


    public function create()
    {
        return view('dashboard.categories.create');
    }

    public function data()
    {
        $model = 'categories';
        $categories = Category::with('photo')->get();
        return DataTables::of($categories)
            ->addColumn('check_item', function ($raw) {
                return '<input type="checkbox" name="items[]" class="check_item" value="' . $raw->id . '">';
            })
            ->addColumn('photo', function ($raw) {
                return '<img width="100" height="80"  src="' . $raw->image . '" >';
            })
            ->addcolumn('actions', function ($raw) use ($model) {

                return view('dashboard.includes.actions', compact('raw', 'model'));
            })
            ->rawColumns(['photo' => 'photo', 'check_item' => 'check_item'])
            ->make(true);

    }//end of data function


    public function store(CategoryRequest $request)
    {

        $data = $request->validated();
        unset($data['photo']);


        $Service = Category::create($data);

        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'categories');
            $Service->photo()->create([
                'src' => $photo,
                'type' => 'Service',
            ]);
        };

        return redirect()->route('categories.index')->with('success', 'تم إضافه البيانات بنجاح');

    }


    public function edit(Category $category)
    {
        return view('dashboard.categories.edit', compact('category'));
    }

    public function update(CategoryRequest $request, Category $category)
    {
        $data = $request->validated();
        unset($data['photo']);
        $category->update($data);
        if ($request->hasFile('photo')) {
            $photo = $this->upload($request->photo, 'categories');
            $category->photo ? $this->deleteOldPhoto('images/categories/', $category->photo->src)
                & $category->photo()->update(['src' => $photo]) : $category->photo()->create(['src' => $photo, 'type' => 'categories']);
        }

        return redirect()->route('categories.index')->with('success', 'تم تعديل البيانات بنجاح');


    }


    public function destroy(Category $category)
    {


        $category->photo ? $this->deleteOldPhoto('images/categories/', $category->photo->src) & $category->photo()->delete() : '';
        Category::destroy($category->id);
        return redirect()->route('categories.index')->with('success', 'تم حذف البيانات بنجاح');
    }

    public function bulkDelete(Request $request)
    {
        foreach ($request->items as $item) {
            $service = Category::findOrFail($item);
            $this->destroy($service);
        }
        Category::destroy($request->items);
        return redirect()->route('categories.index')->with('success', 'تم حذف البيانات بنجاح');


    }//end of bulkDelete function
}

app/Http/Controllers/Website/CategoryController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Page;

class CategoryController extends Controller
{
    public function index()
    {

        $page_title = Page::whereUrl('/categories')->first()->name;

        $categories = Category::with('photo')->get();


        return view('website.pages.categories.index', compact('categories', 'page_title'));

    }//end of index function

    public function show($id)
    {
        $page_title = Page::whereUrl('/categories')->first()->name;
        $category = Category::with('photo')->findOrFail($id);
        $categories = Category::with('photo')->get();
        return view('website.pages.categories.show', compact('category', 'categories', 'page_title'));

    }//end of show function
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="card">
                        <div class="card-header">
                            <h3>إضافه قسم</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{old('title')}}" type="text" name="title" class="form-control">
                                        <span class="input-span">العنوان</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="content" rows="3" class="form-control editor">{{old('content')}}</textarea>
                                        <span class="input-span">المحتوي</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الصورة ( مقاس الصورة -- 670 طول * 770 عرض )</label>
                                        <input id="photo" type="file" name="photo">
                                        <img width="100" id="preview" height="100" src="{{asset('default.svg')}}" alt="">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الأيقون</label>
                                        <select name="icon" id="" class="form-control">
                                            <option value="flaticon-hematology">flaticon hematology</option>
                                            <option value="flaticon-neurology">flaticon neurology</option>
                                            <option value="flaticon-gastroenterology">flaticon gastroenterology</option>
                                            <option value="flaticon-pulmonology">flaticon pulmonology</option>
                                            <option value="flaticon-cardiology">flaticon cardiology</option>
                                            <option value="flaticon-ophthalmology">flaticon ophthalmology</option>
                                        </select>
                                        {{--                                       <i class=" departments-item-icon flaticon-ophthalmology"></i>--}}
                                    </div>
                                </div>
                            </div>


                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor"></textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->
@endsection

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">

                <form action="{{route('categories.update',$category->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                    <div class="card">
                        <div class="card-header">
                            <h3>تعديل قسم</h3>
                        </div>
                        <div class="card-body pb-0">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <input value="{{$category->title}}" type="text" name="title" class="form-control">
                                        <span class="input-span">العنوان</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <textarea name="content" rows="3" class="form-control editor">{{$category->content}}</textarea>
                                        <span class="input-span">المحتوي</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الصورة ( مقاس الصورة -- 670 طول * 770 عرض )</label>
                                        <input id="photo" type="file" name="photo">
                                        <img width="100" id="preview" height="100" src="{{$category->image}}" alt="">
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <div class="input-custom">
                                        <label class="">الأيقون</label>
                                        <select name="icon" id="" class="form-control">
                                            <option {{$category->icon =='flaticon-hematology' ?'selected':''}} value="flaticon-hematology">flaticon hematology</option>
                                            <option {{$category->icon =='flaticon-neurology' ?'selected':''}} value="flaticon-neurology">flaticon neurology</option>
                                            <option {{$category->icon =='flaticon-gastroenterology' ?'selected':''}} value="flaticon-gastroenterology">flaticon gastroenterology</option>
                                            <option {{$category->icon =='flaticon-pulmonology' ?'selected':''}} value="flaticon-pulmonology">flaticon pulmonology</option>
                                            <option {{$category->icon =='flaticon-cardiology' ?'selected':''}} value="flaticon-cardiology">flaticon cardiology</option>
                                            <option {{$category->icon =='flaticon-ophthalmology' ?'selected':''}} value="flaticon-ophthalmology">flaticon ophthalmology</option>
                                        </select>
                                        {{--                                        <i class=" departments-item-icon flaticon-ophthalmology"></i>--}}
                                    </div>
                                </div>
                            </div>

                            <div class="accordion-container">
                                <div class="set">
                                    <a href="#">
                                        بيانات السيو SEO
                                        <i class="fa fa-plus"></i>
                                    </a>
                                    <div class="box-custom">
                                        <div class="flex-divs">
                                            <div class="input-custom">
                                                <input value="{{$category->meta_title}}" type="text" name="meta_title" class="form-control">
                                                <span class="input-span">عنوان الميتا</span>
                                            </div>
                                            <div class="input-custom">
                                                <input value="{{$category->meta_keywords}}" type="text" name="meta_keywords" class="form-control">
                                                <span class="input-span">الكلمات الدلالية</span>
                                            </div>
                                            <div class="input-custom">
                                                <textarea name="meta_description" class="form-control editor">{!! $category->meta_description !!}</textarea>
                                                <span class="input-span">وصف الميتا</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div class="card-footer">
                            <button class="btn ripple btn-primary" type="submit"><i class="fe fe-save"></i> حفظ</button>
                        </div>
                    </div>
                </form>

            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->
@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.master')
@section('content')
    <div class="main-content side-content">
        <div class="container-fluid">
            <div class="inner-body">
                <div class="card">
                    <div class="card-header">
                        <h3>الأقسام</h3>
                        <div class="flex-btns">
                            <a href="" id="delete_all_btn" class="btn ripple btn-danger d-none"><i class="fe fe-trash"></i> حذف الكل </a>
                            <a href="{{route('categories.create')}}" class="btn ripple btn-primary"><i class="fe fe-plus"></i> اضافة </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <form id="bulk_delete" action="{{route('categories.bulkDelete')}}" method="post">
                                @csrf
                                <table class="table datatable table-striped table-bordered">
                                    <thead>
                                    <tr>
                                        <th>
                                            <input type="checkbox" id="check_all">
                                        </th>
                                        <th>#</th>
                                        <th>العنوان</th>
                                        <th>الصورة</th>
                                        <th>العمليات</th>
                                    </tr>
                                    </thead>


                                    <tbody>


                                    </tbody>

                                </table>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div> <!-- End Main Content-->
    </div> <!-- End Page -->

@endsection
@push('js')
    <script>
        var table = $('.table.datatable').DataTable({
            lengthChange: true,

            "processing": true,
            "serverSide": true,
            "ajax": {
                url: '{{route('categories.data')}}',

            },
            "columns": [
                {data: 'check_item', name: 'check_item', sortable: false, searchable: false},
                {data: 'id', name: 'id'},
                {data: 'title', name: 'title'},
                {data: 'photo', name: 'photo'},
                {data: 'actions', name: 'actions'}
            ]


        });

    </script>
@endpush